name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: postgres
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Cache go deps
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashfiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      env:
        GOFLAGS: -mod=mod

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        CONNECTION_STRING: postgres://test:test@localhost:5432/postgres?sslmode=disable
      run:  go test -v -cover -p 1 ./...
